buildscript {scriptHandler->
    apply from: 'repositories.gradle', to: scriptHandler
    apply from: 'dependencies.gradle'
    dependencies {
        classpath(project.ext.build.xtend_android_gradle)
        classpath(project.ext.build.xtext_gradle)
        classpath 'com.android.tools.build:gradle:8.10.0'
        classpath 'org.xtext.xtend:org.xtext.xtend.gradle.plugin:4.0.0'
    }
}

allprojects {
  repositories {
    maven { url System.getenv('ANDROID_HOME') + "/extras/android/m2repository" }
    mavenCentral()
    mavenLocal()
    jcenter()
  }
}

apply plugin: 'org.xtext.xtend'

dependencies {
  implementation project(':Xtendroid')
  implementation project(':XtendroidTest')
  implementation project(':Sample1')
  implementation project(':HelloWorld')
  implementation project(':HandlerExample')
  implementation project(':MovieSearchApp')
}
