name: xtendroid-build

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  source:
    if: ${{ !github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Pack
        run: ./.ci/source.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: artifacts/
  android:
    runs-on: ubuntu-24.04
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: android
      TARGET: universal
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-android-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-
      - name: Set tag name
        run: |
          if [[ "$GITHUB_REF_NAME" =~ ^canary- ]] || [[ "$GITHUB_REF_NAME" =~ ^nightly- ]]; then
              echo "GIT_TAG_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi
          echo $GIT_TAG_NAME
      - name: Update deb repositories
        run: sudo apt-get update
      - name: Install New Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zip unzip python3 ccache apksigner && sudo apt-get clean
      - name: Install JDK 17 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          check-latest: true
      - name: Build
        run: |
          JAVA_HOME=$JAVA_HOME_17_X64 ./gradlew prepareReleaseDependencies
          JAVA_HOME=$JAVA_HOME_17_X64 ./gradlew assembleRelease
        env:
          DROID_KEYSTORE_B64: ${{ secrets.DROID_KEYSTORE_B64 }}
          DROID_KEY_ALIAS: ${{ secrets.DROID_KEY_ALIAS }}
          DROID_KEYSTORE_PASS: ${{ secrets.DROID_KEYSTORE_PASS }}
          DROID_KEY_PASS: ${{ secrets.DROID_KEY_PASS }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.DROID_KEYSTORE_B64 }}
          alias: ${{ secrets.DROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.DROID_KEYSTORE_PASS }}
          keyPassword: ${{ secrets.DROID_KEY_PASS }}
        env:
          BUILD_TOOLS_VERSION: "36.0.0"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OS }}-${{ env.TARGET }}
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
  release:
    runs-on: ubuntu-latest
    needs: [android]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v4
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./**/*.apk","./**/*.aab"]'

